# Generated by Django 5.2.5 on 2025-09-24 05:56

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('homepage', 'Category')
    
    # Create default categories
    default_categories = [
        {'name': 'Meat', 'description': 'Fresh meat products'},
        {'name': 'Fish', 'description': 'Fresh fish and seafood'},
        {'name': 'Veggies', 'description': 'Fresh vegetables'},
        {'name': 'Grocery', 'description': 'General grocery items'},
        {'name': 'Fruit', 'description': 'Fresh fruits'},
    ]
    
    for cat_data in default_categories:
        Category.objects.get_or_create(
            name=cat_data['name'],
            defaults={
                'description': cat_data['description'],
                'is_active': True
            }
        )


def reverse_categories(apps, schema_editor):
    Category = apps.get_model('homepage', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20250924_1154'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_categories),
    ]