# Generated by Django 5.2.5 on 2025-09-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_migrate_product_categories'),
    ]

    operations = [
        # Remove the old category field
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        # Rename category_new to category
        migrations.RenameField(
            model_name='product',
            old_name='category_new',
            new_name='category',
        ),
        # Make category field required (not nullable)
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='homepage.category'),
        ),
    ]
