# Generated by Django 5.2.5 on 2025-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_area_district_division_order_detailed_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
